name: Build MagiskOnWSA
on:
    workflow_dispatch:
        inputs:
            arch:
                description: "WSA Architecture"
                required: true
                default: "x86_64"
                type: choice
                options:
                    - x86_64
                    - ARM64
            release_type:
                description: "WSA Release Channel"
                required: true
                default: "Dev Channel"
                type: choice
                options:
                    - General Availability Channel
                    - Release Preview Channel
                    - Beta Channel
                    - Dev Channel
            magisk_ver:
                description: "Magisk Ver